# Generated by Django 4.1.1 on 2022-11-12 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="course_code"
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="course_name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=10, verbose_name="year")),
                ("semester", models.CharField(max_length=150, verbose_name="semester")),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="student_id"
                    ),
                ),
                ("DOB", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.FileField(upload_to="%y%m%d/")),
                ("website", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecturer",
            fields=[
                (
                    "staff_id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="staff_id"
                    ),
                ),
                ("DOB", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollegeDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "attendance_rate",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="User_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        to="assignment2.class", verbose_name="day_class"
                    ),
                ),
                (
                    "student",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="CollegeDay_student",
                        to="assignment2.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assignment2.course",
                verbose_name="course",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="lecturer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assignment2.lecturer",
                verbose_name="lecturer",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="assignment2.semester",
                verbose_name="semester",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(
                blank=True, to="assignment2.student", verbose_name="Student"
            ),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendance", models.IntegerField()),
                (
                    "collegeday",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignment2.collegeday",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignment2.course",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignment2.lecturer",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignment2.student",
                    ),
                ),
            ],
        ),
    ]
