# Generated by Django 4.1.1 on 2022-11-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignment2", "0003_remove_collegeday_attendance_rate"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.DeleteModel(name="Attendance",),
        migrations.DeleteModel(name="Profile",),
    ]
