# Generated by Django 4.1.1 on 2022-11-13 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assignment2", "0004_remove_profile_user_delete_attendance_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="lecturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assignment2.lecturer",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="student",
            field=models.ManyToManyField(
                blank=True, null=True, to="assignment2.student"
            ),
        ),
    ]
